{
 "title": "Netio Power PDU",
 "description": "Netio power socket monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "netio_target",
    "label": "Netio PDU url",
    "query": "label_values(netio_agent_info,target)"
   },
   {
    "name": "netio_port",
    "label": "Netio Port",
    "query": "label_values(netio_port_state, id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Port load of $netio_target",
   "type": "stat",
   "description": "Current port load of Netio  PDUs",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "repeat": "netio_target",
   "targets": [
    {
     "expr": "netio_port_load_watts{id=~\"$netio_port\"} * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": " P{{id}} ({{name}})"
    }
   ]
  },
  {
   "title": "Port State of $netio_target",
   "type": "gauge",
   "description": "Current port state of Netio  PDUs",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "repeat": "netio_target",
   "targets": [
    {
     "expr": "netio_port_state{id=~\"$netio_port\"} * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": " P{{id}} ({{name}})"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Global load (W)",
   "type": "graph",
   "description": "Total load of the netio PDU",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "netio_global_load_watts * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} ({{model}}, {{sn}})"
    }
   ]
  },
  {
   "title": "Load per port (W)",
   "type": "graph",
   "description": "Current load per port",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "netio_port_load_watts{id=~\"$netio_port\"} * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} - P{{id}} ({{model}}, {{sn}})"
    }
   ]
  },
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Global energy consumption (Wh)",
   "type": "graph",
   "description": "Energy consumed by all ports",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "expr": "netio_global_energy_watthours_total * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} ({{model}}, {{sn}})"
    }
   ]
  },
  {
   "title": "Energy consumption per port (Wh)",
   "type": "graph",
   "description": "Energy consumption breakdown by individual Netio ports",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "expr": "netio_port_energy_watthours_total{id=~\"$netio_port\"} * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} - P{{id}} ({{model}}, {{sn}})"
    }
   ]
  },
  {
   "title": "Rate of global energy consumption",
   "type": "graph",
   "description": "Time derivative of the global consumed energy",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(netio_global_energy_watthours_total[$__interval]) * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} ({{model}}, {{sn}})"
    }
   ]
  },
  {
   "title": "Rate of energy consumption per port",
   "type": "graph",
   "description": "Time derivative of the per port energy breakdown",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(netio_port_energy_watthours_total{id=~\"$netio_port\"}[$__interval]) * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} - P{{id}} ({{model}}, {{sn}})"
    }
   ]
  },
  { "title": "Power factor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Global power factor (no unit, ratio)",
   "type": "graph",
   "description": "Power factor of the whole unit",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "netio_global_power_factor_ratio * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} ({{model}}, {{sn}})"
    }
   ]
  },
  {
   "title": "Power factor per port (no unit, ratio)",
   "type": "graph",
   "description": "Power factor per port",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "netio_port_power_factor_ratio{id=~\"$netio_port\"} * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} - P{{id}} ({{model}}, {{sn}})"
    }
   ]
  },
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Global Current (A)",
   "type": "graph",
   "description": "Current drawn by all ports on the Netio",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "netio_global_current_amperes * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} ({{model}}, {{sn}})"
    }
   ]
  },
  {
   "title": "Current per port  (A)",
   "type": "graph",
   "description": "Current break down by individual ports",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "netio_port_current_amperes{id=~\"$netio_port\"} * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} - P{{id}} ({{model}}, {{sn}})"
    }
   ]
  },
  { "title": "Power grid parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Electricity grid frequency",
   "type": "graph",
   "description": "Inlet power network frequency",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "netio_global_frequency_hertz * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} ({{model}}, {{sn}})"
    }
   ]
  },
  {
   "title": "Electricity grid voltage",
   "type": "graph",
   "description": "Inlet power network voltage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "netio_global_voltage_volts * ON (instance, job) group_left(target, name, model, sn) netio_agent_info{target=~\"$netio_target\"}",
     "legendFormat": "{{name}} ({{model}}, {{sn}})"
    }
   ]
  }
 ]
}